### ISSUE TITLE
Feature: live reload

### ISSUE THREAD

**Issue by wezm** [grapegrip/wool#5]
It would be awesome if when running the built in webserver the preview was live updated when the source file changed. The static site compiler [Zola](https://github.com/getzola/zola) has this feature, perhaps it can serve as inspiration.

**Comment by grapegrip** [comment]
Yes this is definitely a desirable feature. Did not know Zola had it will take a look. Thank you

**Comment by grapegrip** [comment]
@wezm should work now. let me know if you have any problems.

**Comment by wezm** [comment]
Love it! Seems to work well and makes writing with the preview open a seamless experience.
